version: "3.8"

volumes:
  postgres-data: {}
  prometheus_data: {}
  grafana_data: {}

services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: ees/config-server
    environment:
      TZ: 'Europe/Moscow'
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "config-server"
    ports:
      - 8888:8888
    expose:
      - 8888
    restart: unless-stopped

  discovery:
    container_name: discovery
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: ees/discovery-server
    environment:
      TZ: 'Europe/Moscow'
      CONFIG_HOST: config-server
      DISCOVERY_HOST: discovery
      WAIT_HOSTS: config-server:8888
      WAIT_BEFORE_HOSTS: 15
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "discovery"
    ports:
      - 8761:8761
    expose:
      - 8761
    restart: unless-stopped
    depends_on:
      - config-server

  hystrix-dashboard:
    container_name: hystrix-dashboard
    build:
      context: ./hystrix-dashboard
      dockerfile: Dockerfile
    image: ees/hystrix-dashboard
    environment:
      TZ: 'Europe/Moscow'
      CONFIG_HOST: config-server
      DISCOVERY_HOST: discovery
      WAIT_HOSTS: config-server:8888, discovery:8761
      WAIT_HOSTS_TIMEOUT: 60
      WAIT_BEFORE_HOSTS: 30
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "hystrix-dashboard"
    ports:
      - 8788:8788
    expose:
      - 8788
    restart: unless-stopped
    depends_on:
      - config-server
      - discovery

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    environment:
      TZ: 'Europe/Moscow'
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "zipkin"
    ports:
      - 9411:9411
    expose:
      - 9411
    restart: unless-stopped

  db:
    container_name: db
    image: postgres
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: ees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "db"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped

  users:
    container_name: users
    build:
      context: ./microservice-users
      dockerfile: Dockerfile
    image: ees/users
    environment:
      TZ: 'Europe/Moscow'
      CONFIG_HOST: config-server
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_BEFORE_HOSTS: 60
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "users"
    ports:
      - 8081:8081
      - 5006:5005
    expose:
      - 8081
      - 5006
    restart: unless-stopped
    depends_on:
      - config-server
      - db
      - discovery
      - zipkin

  employers:
    container_name: employers
    build:
      context: ./microservice-employers
      dockerfile: Dockerfile
    image: ees/employers
    environment:
      TZ: 'Europe/Moscow'
      CONFIG_HOST: config-server
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_BEFORE_HOSTS: 60
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "employers"
    ports:
      - 8082:8082
      - 5007:5007
    expose:
      - 8082
      - 5007
    restart: unless-stopped
    depends_on:
      - config-server
      - db
      - discovery
      - zipkin

  criteria:
    container_name: criteria
    build:
      context: ./microservice-criteria
      dockerfile: Dockerfile
    image: ees/criteria
    environment:
      TZ: 'Europe/Moscow'
      CONFIG_HOST: config-server
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411
      WAIT_HOSTS_TIMEOUT: 120
      WAIT_BEFORE_HOSTS: 60
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "criteria"
    ports:
      - 8083:8083
      - 5008:5008
    expose:
      - 8083
      - 5008
    restart: unless-stopped
    depends_on:
      - config-server
      - db
      - discovery
      - zipkin

  ui:
    container_name: ui
    build:
      context: ./microservice-ui
      dockerfile: Dockerfile
    image: ees/ui
    environment:
      TZ: 'Europe/Moscow'
      CONFIG_HOST: config-server
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      USERS_HOST: users
      EMPLOYERS_HOST: employers
      CRITERIA_HOST: criteria
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411, users:8081, employers:8082, criteria:8083
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_BEFORE_HOSTS: 150
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "ui"
    ports:
      - 8080:8080
      - 5005:5005
    expose:
      - 80
      - 5005
    restart: unless-stopped
    depends_on:
      - config-server
      - db
      - discovery
      - zipkin
      - users
      - employers
      - criteria

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      TZ: 'Europe/Moscow'
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      TZ: 'Europe/Moscow'
      GF_SECURITY_ADMIN_USER: "${ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${ADMIN_PASSWORD:-admin123}"
      GF_USERS_ALLOW_SIGN_UP: 'false'
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    depends_on:
      - prometheus

  mongo:
    image: mongo:3
    container_name: mongo
    environment:
      TZ: 'Europe/Moscow'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    container_name: elasticsearch
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Europe/Moscow
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g

  graylog:
    image: graylog/graylog:3.3
    container_name: graylog
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - TZ=Europe/Moscow
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
