version: "3.8"

volumes:
  postgres-data:

services:
  config-server:
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    image: ees/config-server
    environment:
      TZ: 'Europe/Moscow'
    ports:
      - 8888:8888
    expose:
      - 8888
    restart: unless-stopped

  db:
    container_name: db
    image: postgres
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: ees
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: unless-stopped

  discovery:
    container_name: discovery
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    image: ees/discovery-server
    environment:
      TZ: 'Europe/Moscow'
      WAIT_HOSTS: config-server:8888
    ports:
      - 8761:8761
    expose:
      - 8761
    restart: unless-stopped

  hystrix-dashboard:
    container_name: hystrix-dashboard
    build:
      context: ./hystrix-dashboard
      dockerfile: Dockerfile
    image: ees/hystrix-dashboard
    environment:
      TZ: 'Europe/Moscow'
      DISCOVERY_HOST: discovery
      WAIT_HOSTS: config-server:8888, discovery:8761
    ports:
      - 8788:8788
    expose:
      - 8788
    restart: unless-stopped
    depends_on:
      - discovery

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    environment:
      TZ: 'Europe/Moscow'
    ports:
      - 9411:9411
    expose:
      - 9411
    restart: unless-stopped

  users:
    container_name: users
    build:
      context: ./microservice-users
      dockerfile: Dockerfile
    image: ees/users
    environment:
      TZ: 'Europe/Moscow'
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411
    ports:
      - 8081:8081
      - 5006:5005
    expose:
      - 8081
      - 5006
    restart: unless-stopped
    depends_on:
      - db
      - discovery
      - zipkin

  employers:
    container_name: employers
    build:
      context: ./microservice-employers
      dockerfile: Dockerfile
    image: ees/employers
    environment:
      TZ: 'Europe/Moscow'
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411
    ports:
      - 8082:8082
      - 5007:5007
    expose:
      - 8082
      - 5007
    restart: unless-stopped
    depends_on:
      - db
      - discovery
      - zipkin

  criteria:
    container_name: criteria
    build:
      context: ./microservice-criteria
      dockerfile: Dockerfile
    image: ees/criteria
    environment:
      TZ: 'Europe/Moscow'
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411
    ports:
      - 8083:8083
      - 5008:5008
    expose:
      - 8083
      - 5008
    restart: unless-stopped
    depends_on:
      - db
      - discovery
      - zipkin

  ui:
    container_name: ui
    build:
      context: ./microservice-ui
      dockerfile: Dockerfile
    image: ees/ui
    environment:
      TZ: 'Europe/Moscow'
      DISCOVERY_HOST: discovery
      ZIPKIN_HOST: zipkin
      USERS_HOST: users
      EMPLOYERS_HOST: employers
      CRITERIA_HOST: criteria
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ees
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      WAIT_HOSTS: config-server:8888, db:5432, discovery:8761, zipkin:9411, users:8081, employers:8082, criteria:8083
    ports:
      - 8080:8080
      - 5005:5005
    expose:
      - 80
      - 5005
    restart: unless-stopped
    depends_on:
      - db
      - discovery
      - zipkin
      - users
      - employers
      - criteria
