-- schema owner
CREATE USER ui WITH password 'ui';

-- schema user
CREATE USER ui_ms WITH password 'ui_ms';

-- create schema
CREATE SCHEMA IF NOT EXISTS ui AUTHORIZATION ui;

GRANT USAGE ON SCHEMA ui TO ui_ms;

ALTER DEFAULT PRIVILEGES FOR USER ui IN SCHEMA ui GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ui_ms;
ALTER DEFAULT PRIVILEGES FOR USER ui IN SCHEMA ui GRANT USAGE ON SEQUENCES TO ui_ms;
ALTER DEFAULT PRIVILEGES FOR USER ui IN SCHEMA ui GRANT EXECUTE ON FUNCTIONS TO ui_ms;
