server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ees?currentSchema=criteria
    username: criteria
    password: criteria

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  sleuth:
    sampler:
      probability: 100

  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:9411

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 2

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    ru.skubatko.dev: TRACE
