server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ees?currentSchema=employers
    username: employers
    password: employers

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    ru.skubatko.dev: TRACE
