global:
  scrape_interval:     15s
  evaluation_interval: 30s
  external_labels:
    monitor: 'monitoring'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
        labels:
          name: prometheus

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'config-server:8888'
        labels:
          name: config-server

  - job_name: 'discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'discovery:8761'
        labels:
          name: discovery

  - job_name: 'hystrix-dashboard'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'hystrix-dashboard:8788'
        labels:
          name: hystrix-dashboard

  - job_name: 'users'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'users:8081'
        labels:
          name: users

  - job_name: 'employers'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'employers:8082'
        labels:
          name: employers

  - job_name: 'criteria'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'criteria:8083'
        labels:
          name: criteria

  - job_name: 'ui'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'ui:8080'
        labels:
          name: ui
