-- schema owner
CREATE USER users WITH password 'users';

-- schema user
CREATE USER users_ms WITH password 'users_ms';

-- create schema
CREATE SCHEMA users AUTHORIZATION users;

GRANT USAGE ON SCHEMA users TO users_ms;

ALTER DEFAULT PRIVILEGES FOR USER users IN SCHEMA users GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO users_ms;
ALTER DEFAULT PRIVILEGES FOR USER users IN SCHEMA users GRANT USAGE ON SEQUENCES TO users_ms;
ALTER DEFAULT PRIVILEGES FOR USER users IN SCHEMA users GRANT EXECUTE ON FUNCTIONS TO users_ms;
