server:
  port: 8082

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:postgres}?currentSchema=employers
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    schema: classpath:db/changelog/00_create_schema.sql
    initialization-mode: always
    continue-on-error: true

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    generate-ddl: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: employers

  sleuth:
    sampler:
      probability: 100

  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:9411

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 2

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

springdoc:
  swagger-ui:
    path: /api
    groups-order: DESC
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
  health:
    defaults:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    ru.skubatko.dev: TRACE
